export default Data = {
    pictures: [{
        id: 1,
        src: require('../img/airplane_travel_trip_vacation_global_speed_path_movement.png')
    },
        {
            id: 2,
            src: require('../img/anchor_safety_decision_secure_position.png')
        }, {
            id: 3,
            src: require('../img/bank_notes_money_finance_commerce_budget_payment_wages_salary.png')
        }, {
            id: 4,
            src: require('../img/bomb_explode_attack_risk_danger_pressure_breakdown.png')
        }, {
            id: 5,
            src: require('../img/brain_intellectual_thinking_intelligence_thought_smart_ideas.png')
        }, {
            id: 6,
            src: require('../img/cactus_dryness_desert_defence_resisting.png')
        }, {
            id: 7,
            src: require('../img/candle_light_energy_belief_hope_trust_glowing.png')
        }, {
            id: 8,
            src: require('../img/carrying_hauling_holding.png')
        }, {
            id: 9,
            src: require('../img/champagne_wine_celebrate_success_begin_party_farewell_welcome_alcohol.png')
        }, {
            id: 10,
            src: require('../img/clover_lucky_special.png')
        }, {
            id: 11,
            src: require('../img/cogs_technology_mechanics_industry_engineer_process.png')
        }, {
            id: 12,
            src: require('../img/compass_orientation_leadership_direction_course.png')
        }, {
            id: 13,
            src: require('../img/coupon_ticket_entry.png')
        }, {
            id: 14,
            src: require('../img/crown_king_domination_award_customer.png')
        }, {
            id: 15,
            src: require('../img/door_opening_opportunity_option_chance_way_out_exit_invite_entrance_unknown_curiosity.png')
        }, {
            id: 16,
            src: require('../img/eye_sense_sight_seeing_attentiveness_visualise_visible_curiosity_interest.png')
        }, {
            id: 17,
            src: require('../img/factory_industry_production_manfacturing_commerce.png')
        }, {
            id: 18,
            src: require('../img/film_camera_projector_cinema_media_movie_television_recording_observe.png')
        }, {
            id: 19,
            src: require('../img/finish_banner_destination_result_victory_end.png')
        }, {
            id: 20,
            src: require('../img/flag_signal_nation_identification_start.png')
        }, {
            id: 21,
            src: require('../img/flipchart_flip_chart_training_workshop_course_presentation_meeting.png')
        }, {
            id: 22,
            src: require('../img/hand_sense_touch_action_activity_manual_craft.png')
        }, {
            id: 23,
            src: require('../img/heavy_overstretched.png')
        }, {
            id: 24,
            src: require('../img/helicopter_rescue_help_outside_view_high_level_overview.png')
        }, {
            id: 25,
            src: require('../img/iceberg_obstacle_unconscious_subconscious_concealed_danger_hidden_cold_risk.png')
        }, {
            id: 26,
            src: require('../img/key_solution_tool_opening_opportunity_secret.png')
        }, {
            id: 27,
            src: require('../img/ladder_help_climb_path_up.png')
        }, {
            id: 28,
            src: require('../img/life_rescue_safety_help_hotline.png')
        }, {
            id: 29,
            src: require('../img/light_bulb_idea_inspiration_innovation_thought_invention_brightness.png')
        }, {
            id: 30,
            src: require('../img/lighthouse_orientation_direction_leadership_signal_effect_light_summary_overview.png')
        }, {
            id: 31,
            src: require('../img/lock_safety_security_password.png')
        }, {
            id: 32,
            src: require('../img/magnet_appeal_attract_bait_attraction_energy_strength.png')
        }, {
            id: 33,
            src: require('../img/magnifying_glass_focus_search_detail_specialisation.png')
        }, {
            id: 34,
            src: require('../img/microphone_speaking_information_journalist_media_news_interview_recording.png')
        }, {
            id: 35,
            src: require('../img/mountain_objective_obstacle_challenge.png')
        }, {
            id: 36,
            src: require('../img/paper_document_note_letter_result_minutes_template_instructions.png')
        }, {
            id: 37,
            src: require('../img/picture_frame_scope_border_context_inside.png')
        }, {
            id: 38,
            src: require('../img/puzzle_piece_part_fitting_interlocking_detail_share_collaborate.png')
        }, {
            id: 39,
            src: require('../img/seal_ribbon_award_first_quality_appreciation.png')
        }, {
            id: 40,
            src: require('../img/shopping_trolley_purchase_consumer_product_sales_retail.png')
        }, {
            id: 41,
            src: require('../img/spider_web_networking_trap_structure_obstacle_catch_centre_network_internet.png')
        }, {
            id: 42,
            src: require('../img/sword_battle_victory_aggression_war_threat.png')
        }, {
            id: 43,
            src: require('../img/syringe_medicine_input_injection_healing_drugs_poison.png')
        }, {
            id: 44,
            src: require('../img/target_objective_hit_solution_clarity.png')
        }, {
            id: 45,
            src: require('../img/tent_tribe_family_ritual_home.png')
        }, {
            id: 46,
            src: require('../img/toy_game_play_role_figure_roleplay.png')
        }, {
            id: 47,
            src: require('../img/treasure_chest_reward_price_value_potential_talent_ability_temptation_riches_objective_goal.png')
        }, {
            id: 48,
            src: require('../img/trophy_award_victory_reward_prize_winner_win.png')
        }, {
            id: 49,
            src: require('../img/truck_transportation_logistics_goods_service_delivery_traffic.png')
        }, {
            id: 50,
            src: require('../img/walking_running.png')
        }, {
            id: 51,
            src: require('../img/watering_can_pour_plant_investment_abundance.png')
        }
    ],
    tags: [{
        name: "workshop",
        pictures: [21]
    }, {
        name: "airplane",
        pictures: [1]
    }, {
        name: "travel",
        pictures: [1]
    }, {
        name: "trip",
        pictures: [1]
    }, {
        name: "vacation",
        pictures: [1]
    }, {
        name: "global",
        pictures: [1]
    }, {
        name: "speed",
        pictures: [1]
    }, {
        name: "path",
        pictures: [1, 27]
    }, {
        name: "movement",
        pictures: [1]
    }, {
        name: "anchor",
        pictures: [2]
    }, {
        name: "safety",
        pictures: [2, 28, 31]
    }, {
        name: "decision",
        pictures: [2]
    }, {
        name: "secure",
        pictures: [2]
    }, {
        name: "position",
        pictures: [2]
    }, {
        name: "bank",
        pictures: [3]
    }, {
        name: "notes",
        pictures: [3]
    }, {
        name: "money",
        pictures: [3]
    }, {
        name: "finance",
        pictures: [3]
    }, {
        name: "commerce",
        pictures: [3, 17]
    }, {
        name: "budget",
        pictures: [3]
    }, {
        name: "payment",
        pictures: [3]
    }, {
        name: "wages",
        pictures: [3]
    }, {
        name: "salary",
        pictures: [3]
    }, {
        name: "bomb",
        pictures: [4]
    }, {
        name: "explode",
        pictures: [4]
    }, {
        name: "attack",
        pictures: [4]
    }, {
        name: "risk",
        pictures: [4, 25]
    }, {
        name: "danger",
        pictures: [4, 25]
    }, {
        name: "pressure",
        pictures: [4]
    }, {
        name: "breakdown",
        pictures: [4]
    }, {
        name: "brain",
        pictures: [5]
    }, {
        name: "intellectual",
        pictures: [5]
    }, {
        name: "thinking",
        pictures: [5]
    }, {
        name: "intelligence",
        pictures: [5]
    }, {
        name: "thought",
        pictures: [5, 29]
    }, {
        name: "smart",
        pictures: [5]
    }, {
        name: "ideas",
        pictures: [5]
    }, {
        name: "cactus",
        pictures: [6]
    }, {
        name: "dryness",
        pictures: [6]
    }, {
        name: "desert",
        pictures: [6]
    }, {
        name: "defence",
        pictures: [6]
    }, {
        name: "resisting",
        pictures: [6]
    }, {
        name: "candle",
        pictures: [7]
    }, {
        name: "light",
        pictures: [7, 29, 30]
    }, {
        name: "energy",
        pictures: [7, 32]
    }, {
        name: "belief",
        pictures: [7]
    }, {
        name: "hope",
        pictures: [7]
    }, {
        name: "trust",
        pictures: [7]
    }, {
        name: "glowing",
        pictures: [7]
    }, {
        name: "carrying",
        pictures: [8]
    }, {
        name: "hauling",
        pictures: [8]
    }, {
        name: "holding",
        pictures: [8]
    }, {
        name: "champagne",
        pictures: [9]
    }, {
        name: "wine",
        pictures: [9]
    }, {
        name: "celebrate",
        pictures: [9]
    }, {
        name: "success",
        pictures: [9]
    }, {
        name: "begin",
        pictures: [9]
    }, {
        name: "party",
        pictures: [9]
    }, {
        name: "farewell",
        pictures: [9]
    }, {
        name: "welcome",
        pictures: [9]
    }, {
        name: "alcohol",
        pictures: [9]
    }, {
        name: "clover",
        pictures: [10]
    }, {
        name: "lucky",
        pictures: [10]
    }, {
        name: "special",
        pictures: [10]
    }, {
        name: "cogs",
        pictures: [11]
    }, {
        name: "technology",
        pictures: [11]
    }, {
        name: "mechanics",
        pictures: [11]
    }, {
        name: "industry",
        pictures: [11, 17]
    }, {
        name: "engineer",
        pictures: [11]
    }, {
        name: "process",
        pictures: [11]
    }, {
        name: "compass",
        pictures: [12]
    }, {
        name: "orientation",
        pictures: [12, 30]
    }, {
        name: "leadership",
        pictures: [12, 30]
    }, {
        name: "direction",
        pictures: [12, 30]
    }, {
        name: "course",
        pictures: [12, 21]
    }, {
        name: "coupon",
        pictures: [13]
    }, {
        name: "ticket",
        pictures: [13]
    }, {
        name: "entry",
        pictures: [13]
    }, {
        name: "crown",
        pictures: [14]
    }, {
        name: "king",
        pictures: [14]
    }, {
        name: "domination",
        pictures: [14]
    }, {
        name: "award",
        pictures: [14, 39, 48]
    }, {
        name: "customer",
        pictures: [14]
    }, {
        name: "door",
        pictures: [15]
    }, {
        name: "opening",
        pictures: [15, 26]
    }, {
        name: "opportunity",
        pictures: [15, 26]
    }, {
        name: "option",
        pictures: [15]
    }, {
        name: "chance",
        pictures: [15]
    }, {
        name: "way",
        pictures: [15]
    }, {
        name: "out",
        pictures: [15]
    }, {
        name: "exit",
        pictures: [15]
    }, {
        name: "invite",
        pictures: [15]
    }, {
        name: "entrance",
        pictures: [15]
    }, {
        name: "unknown",
        pictures: [15]
    }, {
        name: "curiosity",
        pictures: [15, 16]
    }, {
        name: "eye",
        pictures: [16]
    }, {
        name: "sense",
        pictures: [16, 22]
    }, {
        name: "sight",
        pictures: [16]
    }, {
        name: "seeing",
        pictures: [16]
    }, {
        name: "attentiveness",
        pictures: [16]
    }, {
        name: "visualise",
        pictures: [16]
    }, {
        name: "visible",
        pictures: [16]
    }, {
        name: "curiosity",
        pictures: [16]
    }, {
        name: "interest",
        pictures: [16]
    }, {
        name: "factory",
        pictures: [17]
    }, {
        name: "industry",
        pictures: [17]
    }, {
        name: "production",
        pictures: [17]
    }, {
        name: "manfacturing",
        pictures: [17]
    }, {
        name: "commerce",
        pictures: [17]
    }, {
        name: "film",
        pictures: [18]
    }, {
        name: "camera",
        pictures: [18]
    }, {
        name: "projector",
        pictures: [18]
    }, {
        name: "cinema",
        pictures: [18]
    }, {
        name: "media",
        pictures: [18, 34]
    }, {
        name: "movie",
        pictures: [18]
    }, {
        name: "television",
        pictures: [18]
    }, {
        name: "recording",
        pictures: [18, 34]
    }, {
        name: "observe",
        pictures: [18]
    }, {
        name: "finish",
        pictures: [19]
    }, {
        name: "banner",
        pictures: [19]
    }, {
        name: "destination",
        pictures: [19]
    }, {
        name: "result",
        pictures: [19, 36]
    }, {
        name: "victory",
        pictures: [19, 42, 48]
    }, {
        name: "end",
        pictures: [19]
    }, {
        name: "flag",
        pictures: [20]
    }, {
        name: "signal",
        pictures: [20, 30]
    }, {
        name: "nation",
        pictures: [20]
    }, {
        name: "identification",
        pictures: [20]
    }, {
        name: "start",
        pictures: [20]
    }, {
        name: "flipchart",
        pictures: [21]
    }, {
        name: "flip",
        pictures: [21]
    }, {
        name: "chart",
        pictures: [21]
    }, {
        name: "training",
        pictures: [21]
    }, {
        name: "workshop",
        pictures: [21]
    }, {
        name: "course",
        pictures: [21]
    }, {
        name: "presentation",
        pictures: [21]
    }, {
        name: "meeting",
        pictures: [21]
    }, {
        name: "hand",
        pictures: [22]
    }, {
        name: "sense",
        pictures: [22]
    }, {
        name: "touch",
        pictures: [22]
    }, {
        name: "action",
        pictures: [22]
    }, {
        name: "activity",
        pictures: [22]
    }, {
        name: "manual",
        pictures: [22]
    }, {
        name: "craft",
        pictures: [22]
    }, {
        name: "heavy",
        pictures: [23]
    }, {
        name: "overstretched",
        pictures: [23]
    }, {
        name: "helicopter",
        pictures: [24]
    }, {
        name: "rescue",
        pictures: [24, 28]
    }, {
        name: "help",
        pictures: [24, 27, 28]
    }, {
        name: "outside",
        pictures: [24]
    }, {
        name: "view",
        pictures: [24]
    }, {
        name: "high",
        pictures: [24]
    }, {
        name: "level",
        pictures: [24]
    }, {
        name: "overview",
        pictures: [24, 30]
    }, {
        name: "iceberg",
        pictures: [25]
    }, {
        name: "obstacle",
        pictures: [25, 35, 41]
    }, {
        name: "unconscious",
        pictures: [25]
    }, {
        name: "subconscious",
        pictures: [25]
    }, {
        name: "concealed",
        pictures: [25]
    }, {
        name: "danger",
        pictures: [25]
    }, {
        name: "hidden",
        pictures: [25]
    }, {
        name: "cold",
        pictures: [25]
    }, {
        name: "risk",
        pictures: [25]
    }, {
        name: "key",
        pictures: [26]
    }, {
        name: "solution",
        pictures: [26, 44]
    }, {
        name: "tool",
        pictures: [26]
    }, {
        name: "opening",
        pictures: [26]
    }, {
        name: "opportunity",
        pictures: [26]
    }, {
        name: "secret",
        pictures: [26]
    }, {
        name: "ladder",
        pictures: [27]
    }, {
        name: "help",
        pictures: [27, 28]
    }, {
        name: "climb",
        pictures: [27]
    }, {
        name: "path",
        pictures: [27]
    }, {
        name: "up",
        pictures: [27]
    }, {
        name: "life",
        pictures: [28]
    }, {
        name: "rescue",
        pictures: [28]
    }, {
        name: "safety",
        pictures: [28, 31]
    }, {
        name: "help",
        pictures: [28]
    }, {
        name: "hotline",
        pictures: [28]
    }, {
        name: "light",
        pictures: [29, 30]
    }, {
        name: "bulb",
        pictures: [29]
    }, {
        name: "idea",
        pictures: [29]
    }, {
        name: "inspiration",
        pictures: [29]
    }, {
        name: "innovation",
        pictures: [29]
    }, {
        name: "thought",
        pictures: [29]
    }, {
        name: "invention",
        pictures: [29]
    }, {
        name: "brightness",
        pictures: [29]
    }, {
        name: "lighthouse",
        pictures: [30]
    }, {
        name: "orientation",
        pictures: [30]
    }, {
        name: "direction",
        pictures: [30]
    }, {
        name: "leadership",
        pictures: [30]
    }, {
        name: "signal",
        pictures: [30]
    }, {
        name: "effect",
        pictures: [30]
    }, {
        name: "light",
        pictures: [30]
    }, {
        name: "summary",
        pictures: [30]
    }, {
        name: "overview",
        pictures: [30]
    }, {
        name: "lock",
        pictures: [31]
    }, {
        name: "safety",
        pictures: [31]
    }, {
        name: "security",
        pictures: [31]
    }, {
        name: "password",
        pictures: [31]
    }, {
        name: "magnet",
        pictures: [32]
    }, {
        name: "appeal",
        pictures: [32]
    }, {
        name: "attract",
        pictures: [32]
    }, {
        name: "bait",
        pictures: [32]
    }, {
        name: "attraction",
        pictures: [32]
    }, {
        name: "energy",
        pictures: [32]
    }, {
        name: "strength",
        pictures: [32]
    }, {
        name: "magnifying",
        pictures: [33]
    }, {
        name: "glass",
        pictures: [33]
    }, {
        name: "focus",
        pictures: [33]
    }, {
        name: "search",
        pictures: [33]
    }, {
        name: "detail",
        pictures: [33, 38]
    }, {
        name: "specialisation",
        pictures: [33]
    }, {
        name: "microphone",
        pictures: [34]
    }, {
        name: "speaking",
        pictures: [34]
    }, {
        name: "information",
        pictures: [34]
    }, {
        name: "journalist",
        pictures: [34]
    }, {
        name: "media",
        pictures: [34]
    }, {
        name: "news",
        pictures: [34]
    }, {
        name: "interview",
        pictures: [34]
    }, {
        name: "recording",
        pictures: [34]
    }, {
        name: "mountain",
        pictures: [35]
    }, {
        name: "objective",
        pictures: [35, 44, 47]
    }, {
        name: "obstacle",
        pictures: [35, 41]
    }, {
        name: "challenge",
        pictures: [35]
    }, {
        name: "paper",
        pictures: [36]
    }, {
        name: "document",
        pictures: [36]
    }, {
        name: "note",
        pictures: [36]
    }, {
        name: "letter",
        pictures: [36]
    }, {
        name: "result",
        pictures: [36]
    }, {
        name: "minutes",
        pictures: [36]
    }, {
        name: "template",
        pictures: [36]
    }, {
        name: "instructions",
        pictures: [36]
    }, {
        name: "picture",
        pictures: [37]
    }, {
        name: "frame",
        pictures: [37]
    }, {
        name: "scope",
        pictures: [37]
    }, {
        name: "border",
        pictures: [37]
    }, {
        name: "context",
        pictures: [37]
    }, {
        name: "inside",
        pictures: [37]
    }, {
        name: "puzzle",
        pictures: [38]
    }, {
        name: "piece",
        pictures: [38]
    }, {
        name: "part",
        pictures: [38]
    }, {
        name: "fitting",
        pictures: [38]
    }, {
        name: "interlocking",
        pictures: [38]
    }, {
        name: "detail",
        pictures: [38]
    }, {
        name: "share",
        pictures: [38]
    }, {
        name: "collaborate",
        pictures: [38]
    }, {
        name: "seal",
        pictures: [39]
    }, {
        name: "ribbon",
        pictures: [39]
    }, {
        name: "award",
        pictures: [39, 48]
    }, {
        name: "first",
        pictures: [39]
    }, {
        name: "quality",
        pictures: [39]
    }, {
        name: "appreciation",
        pictures: [39]
    }, {
        name: "shopping",
        pictures: [40]
    }, {
        name: "trolley",
        pictures: [40]
    }, {
        name: "purchase",
        pictures: [40]
    }, {
        name: "consumer",
        pictures: [40]
    }, {
        name: "product",
        pictures: [40]
    }, {
        name: "sales",
        pictures: [40]
    }, {
        name: "retail",
        pictures: [40]
    }, {
        name: "spider",
        pictures: [41]
    }, {
        name: "web",
        pictures: [41]
    }, {
        name: "networking",
        pictures: [41]
    }, {
        name: "trap",
        pictures: [41]
    }, {
        name: "structure",
        pictures: [41]
    }, {
        name: "obstacle",
        pictures: [41]
    }, {
        name: "catch",
        pictures: [41]
    }, {
        name: "centre",
        pictures: [41]
    }, {
        name: "network",
        pictures: [41]
    }, {
        name: "internet",
        pictures: [41]
    }, {
        name: "sword",
        pictures: [42]
    }, {
        name: "battle",
        pictures: [42]
    }, {
        name: "victory",
        pictures: [42, 48]
    }, {
        name: "aggression",
        pictures: [42]
    }, {
        name: "war",
        pictures: [42]
    }, {
        name: "threat",
        pictures: [42]
    }, {
        name: "syringe",
        pictures: [43]
    }, {
        name: "medicine",
        pictures: [43]
    }, {
        name: "input",
        pictures: [43]
    }, {
        name: "injection",
        pictures: [43]
    }, {
        name: "healing",
        pictures: [43]
    }, {
        name: "drugs",
        pictures: [43]
    }, {
        name: "poison",
        pictures: [43]
    }, {
        name: "target",
        pictures: [44]
    }, {
        name: "objective",
        pictures: [44, 47]
    }, {
        name: "hit",
        pictures: [44]
    }, {
        name: "solution",
        pictures: [44]
    }, {
        name: "clarity",
        pictures: [44]
    }, {
        name: "tent",
        pictures: [45]
    }, {
        name: "tribe",
        pictures: [45]
    }, {
        name: "family",
        pictures: [45]
    }, {
        name: "ritual",
        pictures: [45]
    }, {
        name: "home",
        pictures: [45]
    }, {
        name: "toy",
        pictures: [46]
    }, {
        name: "game",
        pictures: [46]
    }, {
        name: "play",
        pictures: [46]
    }, {
        name: "role",
        pictures: [46]
    }, {
        name: "figure",
        pictures: [46]
    }, {
        name: "roleplay",
        pictures: [46]
    }, {
        name: "treasure",
        pictures: [47]
    }, {
        name: "chest",
        pictures: [47]
    }, {
        name: "reward",
        pictures: [47, 48]
    }, {
        name: "price",
        pictures: [47]
    }, {
        name: "value",
        pictures: [47]
    }, {
        name: "potential",
        pictures: [47]
    }, {
        name: "talent",
        pictures: [47]
    }, {
        name: "ability",
        pictures: [47]
    }, {
        name: "temptation",
        pictures: [47]
    }, {
        name: "riches",
        pictures: [47]
    }, {
        name: "objective",
        pictures: [47]
    }, {
        name: "goal",
        pictures: [47]
    }, {
        name: "trophy",
        pictures: [48]
    }, {
        name: "award",
        pictures: [48]
    }, {
        name: "victory",
        pictures: [48]
    }, {
        name: "reward",
        pictures: [48]
    }, {
        name: "prize",
        pictures: [48]
    }, {
        name: "winner",
        pictures: [48]
    }, {
        name: "win",
        pictures: [48]
    }, {
        name: "truck",
        pictures: [49]
    }, {
        name: "transportation",
        pictures: [49]
    }, {
        name: "logistics",
        pictures: [49]
    }, {
        name: "goods",
        pictures: [49]
    }, {
        name: "service",
        pictures: [49]
    }, {
        name: "delivery",
        pictures: [49]
    }, {
        name: "traffic",
        pictures: [49]
    }, {
        name: "walking",
        pictures: [50]
    }, {
        name: "running",
        pictures: [50]
    }, {
        name: "watering",
        pictures: [51]
    }, {
        name: "can",
        pictures: [51]
    }, {
        name: "pour",
        pictures: [51]
    }, {
        name: "plant",
        pictures: [51]
    }, {
        name: "investment",
        pictures: [51]
    }, {
        name: "abundance",
        pictures: [51]
    }]
};