export default Data = {
    pictures: [{
        id: 1,
        src: require('../img/1.png')
    },
        {
            id: 2,
            src: require('../img/2.png')
        }, {
            id: 3,
            src: require('../img/3.png')
        }, {
            id: 4,
            src: require('../img/4.png')
        }, {
            id: 5,
            src: require('../img/5.png')
        }, {
            id: 6,
            src: require('../img/6.png')
        }, {
            id: 7,
            src: require('../img/7.png')
        }, {
            id: 8,
            src: require('../img/8.png')
        }, {
            id: 9,
            src: require('../img/9.png')
        }, {
            id: 10,
            src: require('../img/10.png')
        }, {
            id: 11,
            src: require('../img/11.png')
        }, {
            id: 12,
            src: require('../img/12.png')
        }, {
            id: 13,
            src: require('../img/13.png')
        }, {
            id: 14,
            src: require('../img/14.png')
        }, {
            id: 15,
            src: require('../img/15.png')
        }, {
            id: 16,
            src: require('../img/16.png')
        }, {
            id: 17,
            src: require('../img/17.png')
        }, {
            id: 18,
            src: require('../img/18.png')
        }, {
            id: 19,
            src: require('../img/19.png')
        }, {
            id: 20,
            src: require('../img/20.png')
        }, {
            id: 21,
            src: require('../img/21.png')
        }, {
            id: 22,
            src: require('../img/22.png')
        }, {
            id: 23,
            src: require('../img/23.png')
        }, {
            id: 24,
            src: require('../img/24.png')
        }, {
            id: 25,
            src: require('../img/25.png')
        }, {
            id: 26,
            src: require('../img/26.png')
        }, {
            id: 27,
            src: require('../img/27.png')
        }, {
            id: 28,
            src: require('../img/28.png')
        }, {
            id: 29,
            src: require('../img/29.png')
        }, {
            id: 30,
            src: require('../img/30.png')
        }, {
            id: 31,
            src: require('../img/31.png')
        }, {
            id: 32,
            src: require('../img/32.png')
        }, {
            id: 33,
            src: require('../img/33.png')
        }, {
            id: 34,
            src: require('../img/34.png')
        }, {
            id: 35,
            src: require('../img/35.png')
        }, {
            id: 36,
            src: require('../img/36.png')
        }, {
            id: 37,
            src: require('../img/37.png')
        }, {
            id: 38,
            src: require('../img/38.png')
        }, {
            id: 39,
            src: require('../img/39.png')
        }, {
            id: 40,
            src: require('../img/40.png')
        }, {
            id: 41,
            src: require('../img/41.png')
        }, {
            id: 42,
            src: require('../img/42.png')
        }, {
            id: 43,
            src: require('../img/43.png')
        }, {
            id: 44,
            src: require('../img/44.png')
        }, {
            id: 45,
            src: require('../img/45.png')
        }, {
            id: 46,
            src: require('../img/46.png')
        }, {
            id: 47,
            src: require('../img/47.png')
        }, {
            id: 48,
            src: require('../img/48.png')
        }, {
            id: 49,
            src: require('../img/49.png')
        }, {
            id: 50,
            src: require('../img/50.png')
        }, {
            id: 51,
            src: require('../img/51.png')
        }
    ],
    tags: [{
        name: "workshop",
        pictures: [21]
    }, {
        name: "airplane",
        pictures: [1]
    }, {
        name: "travel",
        pictures: [1]
    }, {
        name: "trip",
        pictures: [1]
    }, {
        name: "vacation",
        pictures: [1]
    }, {
        name: "global",
        pictures: [1]
    }, {
        name: "speed",
        pictures: [1]
    }, {
        name: "path",
        pictures: [1, 27]
    }, {
        name: "movement",
        pictures: [1]
    }, {
        name: "anchor",
        pictures: [2]
    }, {
        name: "safety",
        pictures: [2, 28, 31]
    }, {
        name: "decision",
        pictures: [2]
    }, {
        name: "secure",
        pictures: [2]
    }, {
        name: "position",
        pictures: [2]
    }, {
        name: "bank",
        pictures: [3]
    }, {
        name: "notes",
        pictures: [3]
    }, {
        name: "money",
        pictures: [3]
    }, {
        name: "finance",
        pictures: [3]
    }, {
        name: "commerce",
        pictures: [3, 17]
    }, {
        name: "budget",
        pictures: [3]
    }, {
        name: "payment",
        pictures: [3]
    }, {
        name: "wages",
        pictures: [3]
    }, {
        name: "salary",
        pictures: [3]
    }, {
        name: "bomb",
        pictures: [4]
    }, {
        name: "explode",
        pictures: [4]
    }, {
        name: "attack",
        pictures: [4]
    }, {
        name: "risk",
        pictures: [4, 25]
    }, {
        name: "danger",
        pictures: [4, 25]
    }, {
        name: "pressure",
        pictures: [4]
    }, {
        name: "breakdown",
        pictures: [4]
    }, {
        name: "brain",
        pictures: [5]
    }, {
        name: "intellectual",
        pictures: [5]
    }, {
        name: "thinking",
        pictures: [5]
    }, {
        name: "intelligence",
        pictures: [5]
    }, {
        name: "thought",
        pictures: [5, 29]
    }, {
        name: "smart",
        pictures: [5]
    }, {
        name: "ideas",
        pictures: [5]
    }, {
        name: "cactus",
        pictures: [6]
    }, {
        name: "dryness",
        pictures: [6]
    }, {
        name: "desert",
        pictures: [6]
    }, {
        name: "defence",
        pictures: [6]
    }, {
        name: "resisting",
        pictures: [6]
    }, {
        name: "candle",
        pictures: [7]
    }, {
        name: "light",
        pictures: [7, 29, 30]
    }, {
        name: "energy",
        pictures: [7, 32]
    }, {
        name: "belief",
        pictures: [7]
    }, {
        name: "hope",
        pictures: [7]
    }, {
        name: "trust",
        pictures: [7]
    }, {
        name: "glowing",
        pictures: [7]
    }, {
        name: "carrying",
        pictures: [8]
    }, {
        name: "hauling",
        pictures: [8]
    }, {
        name: "holding",
        pictures: [8]
    }, {
        name: "champagne",
        pictures: [9]
    }, {
        name: "wine",
        pictures: [9]
    }, {
        name: "celebrate",
        pictures: [9]
    }, {
        name: "success",
        pictures: [9]
    }, {
        name: "begin",
        pictures: [9]
    }, {
        name: "party",
        pictures: [9]
    }, {
        name: "farewell",
        pictures: [9]
    }, {
        name: "welcome",
        pictures: [9]
    }, {
        name: "alcohol",
        pictures: [9]
    }, {
        name: "clover",
        pictures: [10]
    }, {
        name: "lucky",
        pictures: [10]
    }, {
        name: "special",
        pictures: [10]
    }, {
        name: "cogs",
        pictures: [11]
    }, {
        name: "technology",
        pictures: [11]
    }, {
        name: "mechanics",
        pictures: [11]
    }, {
        name: "industry",
        pictures: [11, 17]
    }, {
        name: "engineer",
        pictures: [11]
    }, {
        name: "process",
        pictures: [11]
    }, {
        name: "compass",
        pictures: [12]
    }, {
        name: "orientation",
        pictures: [12, 30]
    }, {
        name: "leadership",
        pictures: [12, 30]
    }, {
        name: "direction",
        pictures: [12, 30]
    }, {
        name: "course",
        pictures: [12, 21]
    }, {
        name: "coupon",
        pictures: [13]
    }, {
        name: "ticket",
        pictures: [13]
    }, {
        name: "entry",
        pictures: [13]
    }, {
        name: "crown",
        pictures: [14]
    }, {
        name: "king",
        pictures: [14]
    }, {
        name: "domination",
        pictures: [14]
    }, {
        name: "award",
        pictures: [14, 39, 48]
    }, {
        name: "customer",
        pictures: [14]
    }, {
        name: "door",
        pictures: [15]
    }, {
        name: "opening",
        pictures: [15, 26]
    }, {
        name: "opportunity",
        pictures: [15, 26]
    }, {
        name: "option",
        pictures: [15]
    }, {
        name: "chance",
        pictures: [15]
    }, {
        name: "way",
        pictures: [15]
    }, {
        name: "out",
        pictures: [15]
    }, {
        name: "exit",
        pictures: [15]
    }, {
        name: "invite",
        pictures: [15]
    }, {
        name: "entrance",
        pictures: [15]
    }, {
        name: "unknown",
        pictures: [15]
    }, {
        name: "curiosity",
        pictures: [15, 16]
    }, {
        name: "eye",
        pictures: [16]
    }, {
        name: "sense",
        pictures: [16, 22]
    }, {
        name: "sight",
        pictures: [16]
    }, {
        name: "seeing",
        pictures: [16]
    }, {
        name: "attentiveness",
        pictures: [16]
    }, {
        name: "visualise",
        pictures: [16]
    }, {
        name: "visible",
        pictures: [16]
    }, {
        name: "curiosity",
        pictures: [16]
    }, {
        name: "interest",
        pictures: [16]
    }, {
        name: "factory",
        pictures: [17]
    }, {
        name: "industry",
        pictures: [17]
    }, {
        name: "production",
        pictures: [17]
    }, {
        name: "manfacturing",
        pictures: [17]
    }, {
        name: "film",
        pictures: [18]
    }, {
        name: "camera",
        pictures: [18]
    }, {
        name: "projector",
        pictures: [18]
    }, {
        name: "cinema",
        pictures: [18]
    }, {
        name: "media",
        pictures: [18, 34]
    }, {
        name: "movie",
        pictures: [18]
    }, {
        name: "television",
        pictures: [18]
    }, {
        name: "recording",
        pictures: [18, 34]
    }, {
        name: "observe",
        pictures: [18]
    }, {
        name: "finish",
        pictures: [19]
    }, {
        name: "banner",
        pictures: [19]
    }, {
        name: "destination",
        pictures: [19]
    }, {
        name: "result",
        pictures: [19, 36]
    }, {
        name: "victory",
        pictures: [19, 42, 48]
    }, {
        name: "end",
        pictures: [19]
    }, {
        name: "flag",
        pictures: [20]
    }, {
        name: "signal",
        pictures: [20, 30]
    }, {
        name: "nation",
        pictures: [20]
    }, {
        name: "identification",
        pictures: [20]
    }, {
        name: "start",
        pictures: [20]
    }, {
        name: "flipchart",
        pictures: [21]
    }, {
        name: "flip",
        pictures: [21]
    }, {
        name: "chart",
        pictures: [21]
    }, {
        name: "training",
        pictures: [21]
    }, {
        name: "workshop",
        pictures: [21]
    }, {
        name: "course",
        pictures: [21]
    }, {
        name: "presentation",
        pictures: [21]
    }, {
        name: "meeting",
        pictures: [21]
    }, {
        name: "hand",
        pictures: [22]
    }, {
        name: "sense",
        pictures: [22]
    }, {
        name: "touch",
        pictures: [22]
    }, {
        name: "action",
        pictures: [22]
    }, {
        name: "activity",
        pictures: [22]
    }, {
        name: "manual",
        pictures: [22]
    }, {
        name: "craft",
        pictures: [22]
    }, {
        name: "heavy",
        pictures: [23]
    }, {
        name: "overstretched",
        pictures: [23]
    }, {
        name: "helicopter",
        pictures: [24]
    }, {
        name: "rescue",
        pictures: [24, 28]
    }, {
        name: "help",
        pictures: [24, 27, 28]
    }, {
        name: "outside",
        pictures: [24]
    }, {
        name: "view",
        pictures: [24]
    }, {
        name: "high",
        pictures: [24]
    }, {
        name: "level",
        pictures: [24]
    }, {
        name: "overview",
        pictures: [24, 30]
    }, {
        name: "iceberg",
        pictures: [25]
    }, {
        name: "obstacle",
        pictures: [25, 35, 41]
    }, {
        name: "unconscious",
        pictures: [25]
    }, {
        name: "subconscious",
        pictures: [25]
    }, {
        name: "concealed",
        pictures: [25]
    }, {
        name: "danger",
        pictures: [25]
    }, {
        name: "hidden",
        pictures: [25]
    }, {
        name: "cold",
        pictures: [25]
    }, {
        name: "risk",
        pictures: [25]
    }, {
        name: "key",
        pictures: [26]
    }, {
        name: "solution",
        pictures: [26, 44]
    }, {
        name: "tool",
        pictures: [26]
    }, {
        name: "opening",
        pictures: [26]
    }, {
        name: "opportunity",
        pictures: [26]
    }, {
        name: "secret",
        pictures: [26]
    }, {
        name: "ladder",
        pictures: [27]
    }, {
        name: "climb",
        pictures: [27]
    }, {
        name: "path",
        pictures: [27]
    }, {
        name: "up",
        pictures: [27]
    }, {
        name: "life",
        pictures: [28]
    }, {
        name: "hotline",
        pictures: [28]
    }, {
        name: "bulb",
        pictures: [29]
    }, {
        name: "idea",
        pictures: [29]
    }, {
        name: "inspiration",
        pictures: [29]
    }, {
        name: "innovation",
        pictures: [29]
    }, {
        name: "invention",
        pictures: [29]
    }, {
        name: "brightness",
        pictures: [29]
    }, {
        name: "lighthouse",
        pictures: [30]
    }, {
        name: "orientation",
        pictures: [30]
    }, {
        name: "direction",
        pictures: [30]
    }, {
        name: "leadership",
        pictures: [30]
    }, {
        name: "signal",
        pictures: [30]
    }, {
        name: "effect",
        pictures: [30]
    }, {
        name: "summary",
        pictures: [30]
    }, {
        name: "overview",
        pictures: [30]
    }, {
        name: "lock",
        pictures: [31]
    }, {
        name: "security",
        pictures: [31]
    }, {
        name: "password",
        pictures: [31]
    }, {
        name: "magnet",
        pictures: [32]
    }, {
        name: "appeal",
        pictures: [32]
    }, {
        name: "attract",
        pictures: [32]
    }, {
        name: "bait",
        pictures: [32]
    }, {
        name: "attraction",
        pictures: [32]
    }, {
        name: "energy",
        pictures: [32]
    }, {
        name: "strength",
        pictures: [32]
    }, {
        name: "magnifying",
        pictures: [33]
    }, {
        name: "glass",
        pictures: [33]
    }, {
        name: "focus",
        pictures: [33]
    }, {
        name: "search",
        pictures: [33]
    }, {
        name: "detail",
        pictures: [33, 38]
    }, {
        name: "specialisation",
        pictures: [33]
    }, {
        name: "microphone",
        pictures: [34]
    }, {
        name: "speaking",
        pictures: [34]
    }, {
        name: "information",
        pictures: [34]
    }, {
        name: "journalist",
        pictures: [34]
    }, {
        name: "news",
        pictures: [34]
    }, {
        name: "interview",
        pictures: [34]
    }, {
        name: "mountain",
        pictures: [35]
    }, {
        name: "objective",
        pictures: [35, 44, 47]
    }, {
        name: "challenge",
        pictures: [35]
    }, {
        name: "paper",
        pictures: [36]
    }, {
        name: "document",
        pictures: [36]
    }, {
        name: "note",
        pictures: [36]
    }, {
        name: "letter",
        pictures: [36]
    }, {
        name: "minutes",
        pictures: [36]
    }, {
        name: "template",
        pictures: [36]
    }, {
        name: "instructions",
        pictures: [36]
    }, {
        name: "picture",
        pictures: [37]
    }, {
        name: "frame",
        pictures: [37]
    }, {
        name: "scope",
        pictures: [37]
    }, {
        name: "border",
        pictures: [37]
    }, {
        name: "context",
        pictures: [37]
    }, {
        name: "inside",
        pictures: [37]
    }, {
        name: "puzzle",
        pictures: [38]
    }, {
        name: "piece",
        pictures: [38]
    }, {
        name: "part",
        pictures: [38]
    }, {
        name: "fitting",
        pictures: [38]
    }, {
        name: "interlocking",
        pictures: [38]
    }, {
        name: "share",
        pictures: [38]
    }, {
        name: "collaborate",
        pictures: [38]
    }, {
        name: "seal",
        pictures: [39]
    }, {
        name: "ribbon",
        pictures: [39]
    }, {
        name: "award",
        pictures: [39, 48]
    }, {
        name: "first",
        pictures: [39]
    }, {
        name: "quality",
        pictures: [39]
    }, {
        name: "appreciation",
        pictures: [39]
    }, {
        name: "shopping",
        pictures: [40]
    }, {
        name: "trolley",
        pictures: [40]
    }, {
        name: "purchase",
        pictures: [40]
    }, {
        name: "consumer",
        pictures: [40]
    }, {
        name: "product",
        pictures: [40]
    }, {
        name: "sales",
        pictures: [40]
    }, {
        name: "retail",
        pictures: [40]
    }, {
        name: "spider",
        pictures: [41]
    }, {
        name: "web",
        pictures: [41]
    }, {
        name: "networking",
        pictures: [41]
    }, {
        name: "trap",
        pictures: [41]
    }, {
        name: "structure",
        pictures: [41]
    }, {
        name: "catch",
        pictures: [41]
    }, {
        name: "centre",
        pictures: [41]
    }, {
        name: "network",
        pictures: [41]
    }, {
        name: "internet",
        pictures: [41]
    }, {
        name: "sword",
        pictures: [42]
    }, {
        name: "battle",
        pictures: [42]
    }, {
        name: "aggression",
        pictures: [42]
    }, {
        name: "war",
        pictures: [42]
    }, {
        name: "threat",
        pictures: [42]
    }, {
        name: "syringe",
        pictures: [43]
    }, {
        name: "medicine",
        pictures: [43]
    }, {
        name: "input",
        pictures: [43]
    }, {
        name: "injection",
        pictures: [43]
    }, {
        name: "healing",
        pictures: [43]
    }, {
        name: "drugs",
        pictures: [43]
    }, {
        name: "poison",
        pictures: [43]
    }, {
        name: "target",
        pictures: [44]
    }, {
        name: "hit",
        pictures: [44]
    }, {
        name: "clarity",
        pictures: [44]
    }, {
        name: "tent",
        pictures: [45]
    }, {
        name: "tribe",
        pictures: [45]
    }, {
        name: "family",
        pictures: [45]
    }, {
        name: "ritual",
        pictures: [45]
    }, {
        name: "home",
        pictures: [45]
    }, {
        name: "toy",
        pictures: [46]
    }, {
        name: "game",
        pictures: [46]
    }, {
        name: "play",
        pictures: [46]
    }, {
        name: "role",
        pictures: [46]
    }, {
        name: "figure",
        pictures: [46]
    }, {
        name: "roleplay",
        pictures: [46]
    }, {
        name: "treasure",
        pictures: [47]
    }, {
        name: "chest",
        pictures: [47]
    }, {
        name: "reward",
        pictures: [47, 48]
    }, {
        name: "price",
        pictures: [47]
    }, {
        name: "value",
        pictures: [47]
    }, {
        name: "potential",
        pictures: [47]
    }, {
        name: "talent",
        pictures: [47]
    }, {
        name: "ability",
        pictures: [47]
    }, {
        name: "temptation",
        pictures: [47]
    }, {
        name: "riches",
        pictures: [47]
    }, {
        name: "goal",
        pictures: [47]
    }, {
        name: "trophy",
        pictures: [48]
    }, {
        name: "award",
        pictures: [48]
    }, {
        name: "prize",
        pictures: [48]
    }, {
        name: "winner",
        pictures: [48]
    }, {
        name: "win",
        pictures: [48]
    }, {
        name: "truck",
        pictures: [49]
    }, {
        name: "transportation",
        pictures: [49]
    }, {
        name: "logistics",
        pictures: [49]
    }, {
        name: "goods",
        pictures: [49]
    }, {
        name: "service",
        pictures: [49]
    }, {
        name: "delivery",
        pictures: [49]
    }, {
        name: "traffic",
        pictures: [49]
    }, {
        name: "walking",
        pictures: [50]
    }, {
        name: "running",
        pictures: [50]
    }, {
        name: "watering",
        pictures: [51]
    }, {
        name: "can",
        pictures: [51]
    }, {
        name: "pour",
        pictures: [51]
    }, {
        name: "plant",
        pictures: [51]
    }, {
        name: "investment",
        pictures: [51]
    }, {
        name: "abundance",
        pictures: [51]
    }]
};